# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  # dbadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: wesr000@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: example
